#! /bin/bash -e

# directory this script is located in
SCRIPTS=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# some convenient aliases
COMMONER="$SCRIPTS/commoner"
ROOT="$SCRIPTS/.."
BUILD="$ROOT/build"

# relativize everything using commoner
/usr/bin/env node "$COMMONER" --relativize --use-provides-module "$ROOT/src" "$BUILD"

# build js
webpack "$BUILD/Client.js" "$ROOT/static/bundle.js"

# build html
cp "$ROOT/src/front/html/index.html" "$ROOT/static/index.html"
