#!/usr/bin/env node

var ReactTools = require('react-tools');

// do the thing!
require('commoner')
  .ignorePattern(/.*\/__tests__\/.*/)
  .resolve(
    function(id) {
      return context.getProvidedP().then(function(idToPath) {
        // If a module declares its own identifier using @providesModule
        // then that identifier will be a key in the idToPath object.
        if (idToPath.hasOwnProperty(id)) {
          return context.readFileP(idToPath[id]);
        }
      });
    },
    function(id) {
      return this.readModuleP(id);
    }
  ).process(function(id, source) {
    return ReactTools.transform(source, {harmony: true});
  });
